name: Build & Deploy
on:
  push:
    branches:
      - master

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Look Changelog
      uses: jaywcjlove/changelog-generator@v1.4.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|renovate\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: npm install
    - run: npm run install
    - run: npm run build
    - run: npm run build:antdp-base
    - run: npm run build:website

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./packages/antdp/package.json

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.4.3
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.changelog.outputs.tag }}
        tag: ${{ steps.changelog.outputs.tag }}
        body: |
          ```bash
          npm i antdp@${{steps.changelog.outputs.version}}
          npm i @antdp/antdp-ui@${{steps.changelog.outputs.version}}
          npm i @antdp/authorized@${{steps.changelog.outputs.version}}
          npm i @antdp/basic-layouts@${{steps.changelog.outputs.version}}
          npm i @antdp/document-title@${{steps.changelog.outputs.version}}
          npm i @antdp/fullscreen@${{steps.changelog.outputs.version}}
          npm i @antdp/user-login@${{steps.changelog.outputs.version}}
          npm i @antdp/layout-tabs@${{steps.changelog.outputs.version}}
          npm i @antdp/config@${{steps.changelog.outputs.version}}
          npm i @antdp/dependencies@${{steps.changelog.outputs.version}}
          npm i @antdp/page-loading@${{steps.changelog.outputs.version}}
          ```

          ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}

    - run: npm run website:install
    - run: npm run website:build
    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/antdp/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/antdp-ui/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/authorized/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/basic-layouts/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/config/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/dependencies/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/document-title/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/fullscreen/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/layout-tabs/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/page-loading/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/user-login/package.json

    - run: echo ${{ steps.changelog.outputs.tag }}
    - run: mkdir -p examples/website/build/zip
    - name: Compress antdp-base Example.
      run: zip -r -y antdp-base.zip . -x "node_modules/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
      working-directory: examples/antdp-base

    - run: cp -rp examples/antdp-base/antdp-base.zip examples/website/build/zip

    - name: Deploy Website
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./examples/website/build
