name: Build & Deploy
on:
  push:
    branches:
      - master

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - name: Look Changelog
      uses: jaywcjlove/changelog-generator@v1.3.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: npm install
    - run: npm run install:pkg
    - run: npm run build
    - run: npm run install:example
    - run: npm run build:website
    - run: npm run website:install
    - run: npm run website:build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./packages/antdp/package.json

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.3.8
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      if: steps.create_tag.outputs.successful
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.version }}
        release_name: ${{ steps.create_tag.outputs.version }}
        body: |
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Deploy Website
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build